using System;
using System.Security;
using System.Reflection;
using System.Resources;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AllowPartiallyTrustedCallersAttribute()]
#if NET40
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1)]
#endif
[assembly: AssemblyTitleAttribute("Npgsql - .Net Data Provider for PostgreSQL")]
[assembly: AssemblyDescriptionAttribute(".Net Data Provider for PostgreSQL")]
[assembly: AssemblyCompanyAttribute("Npgsql Development Team")]
[assembly: AssemblyProductAttribute("Npgsql")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2002 - 2013 Npgsql Development Team")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("2.0.12.91")]
[assembly: AssemblyFileVersionAttribute("2.0.12.91")]
[assembly: NeutralResourcesLanguageAttribute("en", UltimateResourceFallbackLocation.MainAssembly)]

// Npgsql 5d8b90d52f46fda7
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("NpgsqlEF6, PublicKey=00240000048000009400000006020000002400005253413100040000010001002b3c590b2a4e3d347e6878dc0ff4d21eb056a50420250c6617044330701d35c98078a5df97a62d83c9a2db2d072523a8fc491398254c6b89329b8c1dcef43a1e7aa16153bcea2ae9a471145624826f60d7c8e71cd025b554a0177bd935a7809629f0a7afc778ebb4ad033e1bf512c1a9c6ceea26b077bc46cac93800435e77ee")]
// KU da0cf53beacd9ab5
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("NpgsqlEF6, PublicKey=002400000480000094000000060200000024000052534131000400000100010031ea27e9b8cc48a8d85561b65789c6638cdcfde6ba66628903ebb289b3b2fa863696de55f642de34a4a21373c84589061af9abccb37c2bdca0bc50d53729b661b1da9ba5bea5e529648b62d1f8730f430be62981c37397b7885c66bb5a83626059a67618f3a14f7a58dd3a76cee7a654068897481f7711c8f9f7c0afe917f4db")]
