using System;
using System.Security;
using System.Reflection;
using System.Resources;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AllowPartiallyTrustedCallersAttribute()]
#if NET40
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1)]
#endif
[assembly: AssemblyTitleAttribute("NpgsqlEF6 - .Net EF6 Provider for PostgreSQL")]
[assembly: AssemblyDescriptionAttribute(".Net EF6 Provider for PostgreSQL")]
[assembly: AssemblyCompanyAttribute("Npgsql Development Team, kenjiuno")]
[assembly: AssemblyProductAttribute("NpgsqlEF6")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2002 - 2013 Npgsql Development Team, 2013 kenjiuno")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("2.0.12.91")]
[assembly: AssemblyFileVersionAttribute("2.0.12.91")]
[assembly: NeutralResourcesLanguageAttribute("en", UltimateResourceFallbackLocation.MainAssembly)]
